import type { HelpArticle } from '@/types/help.types'

export const CASH_HELP: HelpArticle = {
  id: 'efectivo',
  title: 'Recibir efectivo, combinar billetes y dar cambio',
  category: 'Vender',
  audience: 'all',
  keywords: ['cobrar', 'dinero', 'selección', 'billetes', 'monedas', 'justo'],
  intro: 'Efectivo recibido es el dinero que entrega el cliente, no el precio de la venta. La app calcula cuánto falta o cuánto cambio debes entregar.',
  steps: [
    'Revisa el total antes de capturar el dinero. Si el cliente entrega exactamente ese importe, toca Justo.',
    'Puedes escribir el importe en Efectivo recibido, o tocar los billetes de $20, $50, $100, $200, $500 y $1,000 y las monedas de $1, $2, $5 y $10.',
    'Cada toque agrega una pieza a su propia selección. Por ejemplo: dos toques en $100 y uno en $50 suman $250. Los contadores muestran cuántas piezas elegiste.',
    'El selector no suma sobre el importe escrito manualmente: al empezar a tocar billetes, el importe corresponde a las piezas seleccionadas. Escribir otro importe o usar Justo puede limpiar esos contadores.',
    'Limpiar selección borra el efectivo y los contadores de billetes y monedas; no quita productos del carrito.',
    'Cuando el efectivo cubra el total, revisa el cambio y toca Cobrar una sola vez. Espera el resultado antes de iniciar otra venta.',
  ],
  tips: [
    'Ejemplo de importe exacto: total $500, efectivo $500, cambio $0. Ejemplo con cambio: total $430, efectivo $500, cambio $70.',
    'Usa punto para centavos: 125.50. La coma sirve para miles: 1,250.50. No uses 125,50: es ambiguo y bloquea el cobro.',
    'Si el efectivo es insuficiente, revisa cuánto falta. No cambies el precio del producto para cuadrar el dinero recibido.',
  ],
}

export const HELP_ARTICLES: readonly HelpArticle[] = [
  {
    id: 'acceso', title: 'Entrar por primera vez y elegir quién atiende', category: 'Comenzar', audience: 'all',
    keywords: ['login', 'contraseña', 'registro', 'solicitud', 'dispositivo', 'miembro'],
    intro: 'Para operar necesitas una cuenta aprobada y un dispositivo y una persona identificados. La solicitud de un negocio nuevo no inicia una sesión automáticamente.',
    steps: [
      'Si el negocio aún no está registrado, envía su solicitud desde la página de registro y espera la aprobación. No repitas la solicitud para intentar saltar la espera.',
      'En la pantalla de inicio de sesión, introduce las credenciales autorizadas del negocio.',
      'Si se solicita, identifica la tablet o teléfono con su acceso de dispositivo. Un socio administra estos accesos en Ajustes → Dispositivos.',
      'En un acceso compartido, elige la persona que realmente atiende en esa sesión. Una cuenta ligada a una persona usa su identidad asignada.',
      'Si el acceso o la persona está inactivo, pide al responsable que revise la situación. No selecciones otra identidad para eludir el bloqueo.',
    ],
    tips: ['No hay recuperación de contraseña desde una opción Olvidé mi contraseña. Consulta al responsable si no puedes entrar; Cambiar mi contraseña requiere una sesión abierta.'],
  },
  {
    id: 'modos', title: 'Modo Venta, Modo Gestión y permisos', category: 'Comenzar', audience: 'all',
    keywords: ['socio', 'colaborador', 'inicio', 'menú', 'ayuda'],
    intro: 'Los modos organizan las pantallas; el rol determina qué acciones puedes realizar. Cambiar a Gestión no convierte a un colaborador en socio.',
    steps: [
      'Usa Venta en el selector lateral para ir directamente a Vender. No necesitas tocar Vender una segunda vez.',
      'Usa Gestión para ir a Inicio y administrar. En una pantalla pequeña y táctil puede aparecer un aviso; confirma solo si necesitas continuar.',
      'En Venta verás Vender como referencia y como enlace para regresar desde Ajustes. En Gestión verás las secciones disponibles para tu rol.',
      'Los colaboradores pueden consultar Productos; crear o editar productos y revisar Reportes, Deudas e Incidencias son tareas de socios.',
      'El engrane del pie abre Ajustes. Ayuda, en la cabecera, está disponible para ambos roles y modos.',
    ],
    tips: ['Antes de cambiar de pantalla durante un cobro, termina o revisa tu trabajo. La ayuda de efectivo junto al carrito se abre sin salir de la venta.'],
  },
  {
    id: 'primera-venta', title: 'Hacer una primera venta de contado', category: 'Vender', audience: 'all',
    keywords: ['buscar', 'categoría', 'cuadrícula', 'lista', 'cobrar'],
    intro: 'Una venta de contado reúne productos, verifica cantidades y registra el efectivo. No basta con agregar productos para que la venta quede cobrada.',
    steps: [
      'Entra a Modo Venta. Busca el producto por su nombre y, si conviene, filtra por categoría.',
      'Elige Cuadrícula para ver las tarjetas o Lista para ver filas compactas. Las dos vistas muestran los mismos productos.',
      'Toca un producto disponible para agregarlo al carrito. Una tarjeta Agotado no se puede agregar.',
      'Revisa los productos, sus cantidades y el total. En celular, avanza al paso de cobro cuando hayas terminado de elegir.',
      'Captura Efectivo recibido, comprueba el cambio y toca Cobrar. Espera el mensaje final: no asumas éxito por ver un botón deshabilitado.',
      'Si el resultado indica pendiente, sin conexión o una respuesta incierta, consulta la sección Sin conexión antes de repetir el cobro.',
    ],
    tips: ['El precio proviene del catálogo. El carrito no ofrece un cambio de precio por venta.'],
  },
  {
    id: 'carrito', title: 'Cambiar cantidades, quitar y vaciar el carrito', category: 'Vender', audience: 'all',
    keywords: ['cantidad', 'única', 'quitar', 'vaciar', 'menos', 'más'],
    intro: 'Revisa el carrito antes de cobrar. La cantidad de piezas puede ser distinta del número de productos diferentes.',
    steps: [
      'Para un producto por cantidad, vuelve a tocarlo en el catálogo o usa el control de aumentar cantidad del carrito.',
      'No puedes superar la existencia disponible. Un producto de pieza única se agrega una sola vez.',
      'Usa el control de disminuir para corregir la cantidad. El mínimo es una pieza; para retirar el producto por completo, toca Quitar.',
      'En pantallas pequeñas puedes abrir Ver productos para comprobar las líneas sin perder de vista el cobro.',
      'Vaciar pide confirmación y elimina todos los productos y el efectivo capturado. Cancela la confirmación si solo querías corregir una línea.',
    ],
    tips: ['Limpiar selección en el efectivo no equivale a Vaciar: conserva los productos.'],
  },
  CASH_HELP,
  {
    id: 'crear-producto', title: 'Crear un producto: pieza única o por cantidad', category: 'Productos', audience: 'socio',
    keywords: ['nuevo', 'nombre', 'precio', 'costo', 'stock', 'existencia'],
    intro: 'Los socios preparan el catálogo desde Productos en Gestión. Decide el tipo y la existencia inicial antes de guardar.',
    steps: [
      'En Gestión abre Productos y toca + Nuevo producto. Escribe un Nombre que permita reconocerlo al vender.',
      'Elige pieza única si solo hay una unidad individual, o por cantidad si varias piezas comparten el mismo producto.',
      'Introduce Precio de venta (MXN). En productos por cantidad, captura la Existencia inicial real: debe ser mayor que cero.',
      'Captura Costo de compra: es obligatorio en productos nuevos y admite 0. Categoría, Proveedor y Notas son opcionales. El costo ayuda a interpretar la utilidad en Reportes.',
      'Puedes añadir una imagen. Revisa todos los datos, toca Crear producto y comprueba que aparece en el catálogo.',
    ],
    tips: ['No crees una cantidad con existencia cero para reponerla después: la app no ofrece un ajuste o reposición manual de existencias.'],
  },
  {
    id: 'editar-producto', title: 'Editar, desactivar y reactivar productos', category: 'Productos', audience: 'socio',
    keywords: ['editar', 'desactivar', 'reactivar', 'inactivos', 'existencia', 'precio'],
    intro: 'Editar corrige los datos permitidos del catálogo. Desactivar retira un producto de la oferta sin tratarlo como una venta.',
    steps: [
      'En Productos identifica la tarjeta o fila correcta y toca Editar. Revisa nombre, precio y los campos editables antes de guardar.',
      'El tipo y la existencia inicial no se modifican después de crear el producto. No uses el formulario para simular una entrada de mercancía.',
      'Para dejar de ofrecerlo, usa Desactivar y revisa el resultado. Un producto inactivo se distingue por su estado.',
      'Activa Mostrar inactivos para encontrarlo de nuevo; usa Reactivar si debe volver a ofrecerse.',
      'Al cambiar el precio, comprueba el catálogo actualizado antes de comenzar otra venta.',
    ],
    tips: ['No hay ajuste de existencia, merma ni reversión de ventas desde Editar. Resolver una incidencia tampoco repone stock.'],
  },
  {
    id: 'fotos', title: 'Añadir o cambiar la foto de un producto', category: 'Productos', audience: 'socio',
    keywords: ['foto', 'imagen', 'jpeg', 'png', 'webp', 'heic', '5mb'],
    intro: 'Una imagen ayuda a reconocer el producto; no cambia su tipo, cantidad o precio.',
    steps: [
      'Abre el formulario de creación o Editar del producto y busca Imagen del producto (opcional).',
      'Elige una imagen JPEG, PNG o WebP que no supere 5 MB.',
      'Si el teléfono ofrece HEIC, conviértela a uno de los formatos admitidos antes de cargarla.',
      'Comprueba la vista previa y guarda el formulario. Revisa la tarjeta para confirmar que muestra la imagen elegida.',
    ],
    tips: ['Si se rechaza la foto, revisa su formato y tamaño; cambiar solamente la extensión no convierte la imagen. Guardar el producto y subir la imagen son pasos separados: si falla solo la foto, el producto puede haberse guardado. Búscalo antes de crear otro.'],
  },
  {
    id: 'imprimir-qr', title: 'Preparar e imprimir etiquetas QR', category: 'Productos', audience: 'all',
    keywords: ['etiquetas', 'selección', 'pdf', 'a4', 'calibración', 'codigo qr'],
    intro: 'Las etiquetas identifican los productos al escanear en Venta. Un socio tiene la pantalla Códigos QR; en Productos, cualquier rol en Gestión puede usar las etiquetas de productos seleccionados.',
    steps: [
      'En Gestión abre Productos y usa la selección para marcar los productos que necesitan etiqueta; un inactivo no se marca.',
      'Revisa cuáles elegiste antes de generar las etiquetas. Si eres socio, también puedes usar la pantalla Códigos QR.',
      'En Códigos QR busca y agrega cada producto a Tu lista de impresión. Volver a agregarlo aumenta las copias; usa los controles de cantidad o Quitar para corregir la lista.',
      'Toca Imprimir códigos QR y luego Vista previa o Descargar PDF. Verifica nombres y códigos. Una hoja A4 admite hasta 72 etiquetas.',
      'Imprime a tamaño real, escala 100%, sin ajustar a la página. Haz primero una prueba en papel normal.',
      'Si no coincide con tus etiquetas, ajusta Margen superior (mm), Margen izquierdo (mm) o Alto de fila (mm). Restablecer vuelve a los ajustes iniciales. Prueba otra hoja antes de gastar etiquetas.',
      'Pega la etiqueta en el producto correcto y prueba el QR con el lector de Vender.',
    ],
    tips: ['No sustituyas el QR generado por un código de barras comercial. Comprueba que el lector agrega el producto esperado.'],
  },
  {
    id: 'crear-deuda', title: 'Registrar fiado o apartado desde una venta', category: 'Deudas', audience: 'socio',
    keywords: ['deudor', 'cliente', 'abono inicial', 'fiado', 'apartado', 'una línea'],
    intro: 'Fiado entrega el producto y deja un saldo por cobrar. Apartado reserva el producto. Registrar estas operaciones corresponde a socios, aunque el ofrecimiento pueda aparecer en el carrito de un colaborador.',
    steps: [
      'Deja en el carrito una sola línea de producto con la cantidad correcta. Un fiado o apartado no reúne varios productos diferentes.',
      'Cuando falta efectivo y el importe no es ambiguo, abre la opción de registrar fiado o apartado. Si no eres socio, pide al socio que lo gestione.',
      'Elige Fiado o Apartado según si entregas o reservas el producto. Captura los datos del deudor y revisa producto, cantidad y total.',
      'Escribe el abono inicial de forma explícita, incluido 0 si no recibes dinero. No supongas que el efectivo del carrito se copiará al abono.',
      'Si acuerdan fechas, activa ¿Quieres programar fechas de pago? antes de registrar. Revisa las fechas y los importes; + Agregar fecha de pago añade otra cuota.',
      'Confirma el registro y lee su resultado. Si queda pendiente sin conexión, conserva la cuenta y el dispositivo originales para sincronizar.',
    ],
    tips: ['El abono inicial no se hereda del efectivo recibido. No documentes la operación como cobrada hasta revisar su resultado. No hay cancelación ni edición de una deuda registrada.'],
  },
  {
    id: 'abonos', title: 'Consultar una deuda y registrar un abono', category: 'Deudas', audience: 'socio',
    keywords: ['saldo', 'pagar', 'liquidar', 'deudor', 'pendiente'],
    intro: 'Deudas muestra operaciones activas o pendientes. Para saldar una deuda se registra un abono por el saldo completo; no hay un botón independiente Liquidar.',
    steps: [
      'En Gestión abre Deudas y localiza la operación. Verifica el nombre del deudor, producto y tipo antes de abrir su detalle.',
      'Revisa el total, los abonos y el saldo actual; no uses solamente el importe original para decidir cuánto falta.',
      'Para registrar dinero recibido, usa el formulario de abono del detalle y captura el importe real.',
      'Confirma con conexión y revisa la respuesta. Los abonos posteriores se registran directamente en línea, no mediante la cola de creación offline.',
      'Para pagar todo, registra un abono por el saldo completo. La operación deja de ser pendiente conforme al resultado registrado.',
    ],
    tips: ['No hay cancelación, edición general ni una vista de historial de deudas liquidadas en esta pantalla. No repitas un abono ante una respuesta incierta sin verificar su resultado.'],
  },
  {
    id: 'calendario', title: 'Preparar y consultar fechas de cuotas', category: 'Deudas', audience: 'socio',
    keywords: ['calendario', 'cuotas', 'fecha', 'vencimiento', 'atrasada'],
    intro: 'El calendario refleja las cuotas acordadas. Las fechas opcionales se preparan al crear el fiado o apartado, no se reprograman después.',
    steps: [
      'Al registrar la deuda, activa ¿Quieres programar fechas de pago? si necesitas un calendario, antes de confirmar.',
      'Elige Fechas de pago y revisa el importe sugerido de cada cuota. + Agregar fecha de pago añade otra fila; puedes cambiar su importe y usar Quitar para corregirla.',
      'Después, abre Deudas y consulta su calendario o detalle para identificar fechas y pagos pendientes.',
      'Si aparece un atraso, revisa los abonos y el saldo. Una fecha del calendario no registra por sí sola un pago.',
    ],
    tips: ['El calendario posterior es de consulta: no ofrece cambiar fechas o editar el plan de una deuda ya creada.'],
  },
  {
    id: 'incidencias', title: 'Revisar y resolver incidencias detectadas', category: 'Administrar', audience: 'socio',
    keywords: ['conflicto', 'stock', 'fecha', 'resolver', 'notas'],
    intro: 'Incidencias reúne conflictos detectados por el sistema, como problemas de existencias o fechas. No es un formulario para dar de alta cualquier ajuste.',
    steps: [
      'En Gestión abre Incidencias y usa sus filtros para encontrar los pendientes que debes revisar.',
      'Abre el detalle y lee los datos del conflicto antes de marcarlo resuelto.',
      'Investiga la operación con el equipo. Captura las notas de resolución que expliquen lo revisado.',
      'Confirma la resolución y verifica que el estado de la incidencia cambió.',
    ],
    tips: ['Resolver una incidencia no devuelve dinero, revierte una venta ni ajusta existencias automáticamente.'],
  },
  {
    id: 'reportes', title: 'Leer reportes y descargar PDF o Excel', category: 'Administrar', audience: 'socio',
    keywords: ['ventas', 'abonos', 'utilidad', 'costo', 'fechas', 'exportar', 'excel', 'pdf'],
    intro: 'Reportes combina ventas de contado y abonos. El ingreso cobrado, la utilidad y el número de ventas no son la misma medida.',
    steps: [
      'En Gestión abre Reportes y elige el periodo que quieres revisar.',
      'Lee los desgloses Por persona y Por producto para entender quién vendió y qué productos se vendieron; son tablas de resultados, no filtros de búsqueda.',
      'Revisa las ventas de contado y el desglose de abonos; distingue lo vendido de lo cobrado en ese periodo.',
      'Si hay productos sin costo de compra, lee el aviso de utilidad incompleta: no interpretes esa cifra como una ganancia definitiva.',
      'Para compartir la consulta, elige la descarga PDF o Excel disponible y revisa el periodo y contenido del archivo.',
    ],
    tips: ['La exportación se habilita cuando hay ventas de contado en la consulta. Un periodo con solo abonos puede mostrar información y aun así no permitir descargar el reporte.'],
  },
  {
    id: 'equipo', title: 'Consultar Mi equipo y agregar una persona', category: 'Ajustes', audience: 'socio',
    keywords: ['miembro', 'colaborador', 'socio', 'comisión', 'persona'],
    intro: 'Mi equipo identifica a las personas que trabajan en el negocio. Es una pantalla de socios, disponible desde Ajustes en ambos modos.',
    steps: [
      'Abre el engrane de Ajustes y entra a Mi equipo.',
      'Revisa la lista para evitar agregar a la misma persona otra vez.',
      'Usa el formulario para agregar una persona y captura los datos y la comisión que corresponda.',
      'Guarda y verifica la nueva persona en la lista. En accesos compartidos, elige a quien realmente atiende al iniciar su sesión.',
    ],
    tips: ['La pantalla permite agregar y consultar; no ofrece editar un miembro existente ni un perfil general de la cuenta.'],
  },
  {
    id: 'dispositivos', title: 'Registrar un dispositivo y administrar su acceso', category: 'Ajustes', audience: 'socio',
    keywords: ['tablet', 'teléfono', 'código', 'correo', 'email', 'revocar', 'reemitir'],
    intro: 'Dispositivos controla los accesos de las tablets y teléfonos del negocio. Protege los códigos y compártelos solo con quien deba usarlos.',
    steps: [
      'En Ajustes abre Dispositivos y registra el equipo con un nombre que lo distinga.',
      'Usa el código y las opciones de correo disponibles para entregar el acceso a la persona que configurará ese equipo.',
      'Identifica el dispositivo en la pantalla de selección de contexto cuando la app lo pida.',
      'Si un acceso ya no debe utilizarse, revócalo. Para emitir uno nuevo usa Reemitir en el dispositivo correcto.',
      'Si revocas o reemplazas el acceso del dispositivo que estás usando, prepárate para su desconexión y una nueva identificación.',
    ],
    tips: ['Revisa el nombre del dispositivo antes de revocar o reemitir: puede interrumpir una sesión en curso. No compartas códigos en lugares públicos.'],
  },
  {
    id: 'contrasena', title: 'Cambiar mi contraseña con la sesión abierta', category: 'Ajustes', audience: 'all',
    keywords: ['contraseña', 'clave', 'seguridad', 'login'],
    intro: 'Cada persona autenticada puede abrir Cambiar mi contraseña desde Ajustes. Esto no es un procedimiento de recuperación de una cuenta cerrada.',
    steps: [
      'Abre el engrane y entra a Cambiar mi contraseña.',
      'Completa los campos que pide el formulario y escribe una contraseña nueva de 10 a 128 caracteres.',
      'Revisa la confirmación de la nueva contraseña antes de enviar el formulario.',
      'Espera el resultado y conserva la nueva contraseña de forma segura para el siguiente inicio de sesión.',
    ],
    tips: ['No existe una opción de restablecimiento por Olvidé mi contraseña. Si ya no puedes entrar, consulta al responsable.'],
  },
  {
    id: 'instalar', title: 'Instalar la app en una tablet o teléfono', category: 'Comenzar', audience: 'all',
    keywords: ['pwa', 'instalar', 'inicio', 'ios', 'navegador'],
    intro: 'Instalar crea un acceso a La Marchanta. La opción depende del navegador y del dispositivo; no reemplaza la conexión cuando una operación la requiere.',
    steps: [
      'Abre La Marchanta en el navegador del dispositivo y busca Instalar app cuando esté disponible.',
      'Si la barra está colapsada, expándela para ver la acción de instalación.',
      'Sigue el aviso de instalación que ofrezca el navegador. En iOS, sigue las indicaciones para añadirla a la pantalla de inicio.',
      'Abre el acceso instalado y revisa tu sesión y contexto antes de vender.',
    ],
    tips: ['Si no aparece la opción, ese navegador puede no ofrecer instalación en ese momento. Instalar no garantiza que todos los datos u operaciones funcionen sin internet.'],
  },
  {
    id: 'preguntas', title: 'Preguntas frecuentes y límites actuales', category: 'Comenzar', audience: 'all',
    keywords: ['no aparece', 'permiso', 'precio', 'ajustar', 'devolución', 'cancelar', 'historial'],
    intro: 'Cuando no encuentres una acción, verifica primero el modo, el rol y el estado de la operación. No todas las tareas de un negocio están implementadas.',
    steps: [],
    questions: [
      { question: '¿Por qué no aparece una sección?', answer: 'Revisa si estás en Venta o Gestión y si tu rol es socio. Ayuda se puede leer con ambos roles.' },
      { question: '¿Por qué no se agrega un producto?', answer: 'Comprueba su disponibilidad y si es una pieza única que ya está en el carrito. Disponible permite agregarlo; Agotado no.' },
      { question: '¿Por qué no se habilita Cobrar?', answer: 'El carrito necesita productos y efectivo claro que cubra el total. También se bloquea mientras hay un cobro en curso.' },
      { question: '¿Por qué no se descarga un reporte?', answer: 'Revisa la conexión y si el periodo contiene ventas de contado; solo abonos no habilita la exportación.' },
      { question: '¿Puedo ajustar stock, devolver una venta o cancelar una deuda?', answer: 'La app no ofrece ajustes de stock, mermas, devoluciones posteriores a una venta, cancelación de deudas ni edición de cuotas. Consulta al responsable.' },
    ],
    tips: ['No hay una ruta de historial general, reservas internas ni un perfil general editable. No uses otra pantalla para simular una función que no existe.'],
  },
  {
    id: 'escanear', title: 'Agregar un producto con su código QR', category: 'Vender', audience: 'all',
    keywords: ['codigo qr', 'cámara', 'escanear', 'etiqueta', 'uuid'],
    intro: 'El lector reconoce etiquetas QR de productos de La Marchanta. No es un lector de cualquier código comercial de barras.',
    steps: [
      'En Vender abre el lector de QR y permite el acceso a la cámara cuando el navegador lo solicite.',
      'Apunta a una etiqueta QR generada para un producto del negocio. El código contiene el identificador del producto.',
      'Mantén el código completo dentro del encuadre, con buena iluminación y sin reflejos.',
      'Revisa el producto encontrado y el carrito. Si el producto está agotado o no se reconoce, búscalo por nombre y verifica la etiqueta.',
    ],
    tips: ['Un código de barras comercial o un QR ajeno sin identificador válido no identifica un producto de La Marchanta. El lector puede reconocer un identificador válido dentro de otro texto; eso no garantiza que cualquier QR o dirección web funcione. Si la cámara no abre, revisa sus permisos.'],
  },
  {
    id: 'sin-conexion', title: 'Sin conexión, ventas pendientes y respuestas inciertas', category: 'Vender', audience: 'all',
    keywords: ['offline', 'internet', 'sincronización', 'pendiente', 'reintentar', 'duplicado'],
    intro: 'La app puede guardar trabajo pendiente y usar una copia del catálogo. La información local no garantiza que una operación ya fue aceptada.',
    steps: [
      'Comprueba si el catálogo indica que usa una copia guardada: necesita haberse cargado antes en ese navegador y sus existencias pueden no estar actualizadas.',
      'Al cobrar, lee el resultado. Una operación guardada o pendiente debe sincronizarse; no equivale a una confirmación definitiva.',
      'Si se corta la conexión o no sabes si se recibió el cobro, no repitas la venta por impulso. Revisa el indicador de pendientes y el resultado disponible.',
      'Vuelve a conectarte y revisa la sincronización automática y el indicador de pendientes. No borres los datos del navegador mientras tengas operaciones guardadas.',
      'Si hay Ventas por revisar, toca Ver y lee el motivo. Entendido descarta el aviso tras leerlo: no reenvía la venta ni confirma un cobro.',
      'Los fiados y apartados guardados de otra sesión necesitan la cuenta y el dispositivo originales. Vuelve a ese contexto para sincronizarlos.',
    ],
    tips: ['Guardar una venta sin conexión no confirma su aceptación ni asegura que la existencia siga disponible. Un conflicto puede requerir revisión de un socio.'],
  },
]

/** Audit evidence is never rendered or indexed as reader-facing help text. */
export const HELP_EVIDENCE: Readonly<Record<string, readonly string[]>> = {
  'crear-producto': ['src/components/ui/organisms/ProductForm.vue', 'src/views/products/ProductCatalogView.vue'],
  'editar-producto': ['src/components/ui/organisms/ProductForm.vue', 'src/views/products/ProductCatalogView.vue'],
  fotos: ['src/components/ui/organisms/ProductForm.vue'],
  'imprimir-qr': ['src/views/products/CodigosQrView.vue', 'src/components/ui/organisms/LabelPrintDialog.vue'],
  'crear-deuda': ['src/components/ui/organisms/RegistrarDeudaModal.vue', 'src/views/sales/SaleView.vue'],
  abonos: ['src/components/ui/organisms/DeudaDetailModal.vue'],
  calendario: ['src/components/ui/molecules/CuotasPlaneadasEditor.vue', 'src/views/deudas/DeudasView.vue'],
  incidencias: ['src/views/incidencias/IncidenciasView.vue'],
  reportes: ['src/views/reports/ReportsView.vue'],
  equipo: ['src/views/settings/TeamView.vue'],
  dispositivos: ['src/views/settings/DevicesView.vue'],
  contrasena: ['src/views/settings/ChangePasswordView.vue'],
  instalar: ['src/components/ui/molecules/InstallAppButton.vue'],
  preguntas: ['src/router/index.ts', 'src/components/ui/organisms/SaleCart.vue'],
  acceso: ['src/views/SelectContextView.vue', 'src/stores/auth.store.ts'],
  modos: ['src/layouts/AppLayout.vue', 'src/layouts/nav-items.ts'],
  'primera-venta': ['src/views/sales/SaleView.vue', 'src/components/ui/organisms/SaleCatalogPicker.vue'],
  carrito: ['src/components/ui/organisms/SaleCart.vue', 'src/stores/cart.store.ts'],
  efectivo: ['src/components/ui/molecules/CashInput.vue', 'src/components/ui/molecules/CashDenominationPad.vue', 'src/utils/money.ts'],
  escanear: ['src/views/sales/SaleView.vue'],
  'sin-conexion': ['src/stores/sales-queue.store.ts', 'src/services/sales-sync.ts'],
}
